package webservices.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "ReceivingOrdersSOAP", targetNamespace = "http://webservices/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface ReceivingOrdersSOAP {


    /**
     * @param request
     * @return returns webservices.client.RecOrderResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://webservices/", className = "webservices.client.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://webservices/", className = "webservices.client.RegisterResponse")
    @Action(input = "http://webservices/ReceivingOrdersSOAP/registerRequest", output = "http://webservices/ReceivingOrdersSOAP/registerResponse")
    public RecOrderResponse register(
            @WebParam(name = "request", targetNamespace = "")
            RecOrderRequest request);

}
